menu config

diff --git a/menu_options b/menu_options
--- a/menu_options
+++ b/menu_options
@@ -8,7 +8,7 @@ notification_urgent="dunstify -u critical"
 
 menu_main() {
   # Define first layer
-  options=(" Wifi" "󰂯 Bluetooth" "󰕾 Audio" "󰍹 Monitors" "󰓶 Tablet-Mode" " Light" "󰐦 Energy-Mode" " Themes" "  server" "󱊞 USB" " Updates" "󰅙 Close")
+  options=(" Wifi" "󰂯 Bluetooth" "󰕾 Audio" "󰍹 Monitors" " Light" "󰓅 Energy-Mode" "󱊞 USB" " Nixos Config" "󰅙 Close")
 
   # display options
   selected=$(printf '%s\n' "${options[@]}" | ${menu} " Settings")
@@ -24,27 +24,18 @@ menu_main() {
     menu_vol
     ;;
   "󰍹 Monitors")
-    menu_mon
-    ;;
-  "󰓶 Tablet-Mode")
-    menu_tablet
+    nwg-displays
     ;;
   " Light")
     menu_light
     ;;
-  "󰐦 Energy-Mode")
+  "󰓅 Energy-Mode")
     menu_energy
-    ;;
-  " Themes")
-    menu_themes
-    ;;
-  "  server")
-    menu_server
     ;;
   "󱊞 USB")
     menu_usb
     ;;
-  " Updates")
+  " Nixos Config")
     menu_updates
     ;;
   "󰅙 Close") ;;
@@ -684,102 +675,6 @@ menu_vol() {
 
 }
 
-menu_mon() {
-
-  monitor_count=$(xrandr --listmonitors | awk 'NR==1 {print $2}')
-  monitor_array=($(xrandr | grep -w connected | awk '{print $1}'))
-  echo $monitor_count
-  echo ${monitor_array[0]}
-  echo ${monitor_array[1]}
-  monitor_array+=("Go back")
-
-  options=("Rearrange monitors" "Go back")
-  selected=$(printf '%s\n' "${options[@]}" | ${menu_alt})
-
-  case $selected in
-
-  "Rearrange monitors")
-
-    selected_main=$(printf '%s\n' "${monitor_array[@]}" | ${menu} "Select main")
-
-    if [[ ! "$selected_main" == "Go back" ]]; then
-      # delete main from array
-      monitor_array=("${monitor_array[@]/$selected_main/}")
-      string_command="xrandr --output "
-    fi
-
-    while true; do
-
-      options=("Add another monitor" "Output current configuration" "Go back")
-
-      selected_options=$(printf '%s\n' "${options[@]}" | ${menu_alt})
-
-      case $selected_options in
-
-      "Add another monitor")
-
-        another_mon=$(printf '%s\n' "${monitor_array[@]}" | ${menu_alt})
-
-        if [[ ! "$another_mon" == "Go back" ]]; then
-
-          monitor_array=("${monitor_array[@]/$another_mon/}")
-        else
-          menu_mon
-        fi
-
-        options_pos=("above" "below" "right-of" "left-of" "Go back")
-
-        next_mon_pos=$(printf '%s\n' "${options_pos[@]}" | ${menu_alt})
-
-        case $next_mon_pos in
-
-        "Go back")
-          menu_mon
-          break
-          ;;
-        *)
-          echo $string_command
-
-          string_command+="$another_mon --$next_mon_pos "
-          echo $string_command
-          # break, since i dont know how to handle three-->what should string_command look like?
-          ;;
-        esac
-
-        ;;
-
-      "Output current configuration")
-        # turn everything else off:
-        new_mon_arr=($(xrandr | grep -w disconnected | awk '{print $1}'))
-        for mon in ${new_mon_arr[@]}; do
-          echo "xrandr --output $mon --off"
-          xrandr --output $mon --off
-        done
-
-        string_command+="$selected_main"
-        $string_command --auto
-        echo $string_command
-        xwallpaper --zoom ~/.config/wall/picture &
-
-        break
-        ;;
-
-      "Go back")
-        menu_mon
-        break
-        ;;
-      esac
-    done
-
-    ;;
-
-  "Go back")
-    menu_main
-    ;;
-  esac
-
-}
-
 menu_tablet() {
 
   status_kb=$(xinput list-props 12 | grep "Device Enabled" | awk '{print $4}')
@@ -1103,15 +998,19 @@ menu_usb() {
 
 menu_updates() {
 
-  updates=$(pacman -Qu | wc -l)
-  options=("Update $updates packages" "  Go back")
+  options=("Edit Config" "Update Sources" "Build System" "  Go back")
 
   selected=$(printf '%s\n' "${options[@]}" | ${menu_alt})
 
   case $selected in
-  "Update $updates packages")
-    st -e bash -c "
-            sudo pacman --noconfirm -Syu && ${notification_normal} System 'Up to date!'"
+  "Edit Config")
+    foot -e bash -c "cd /home/falk/nix-conf && nvim"
+    ;;
+  "Update Sources")
+    foot -e bash -c "nix flake update --flake /home/falk/nix-conf scripts && echo \"==> Completed\" || echo \"==> Failed\"; read -p \"Press Key to Exit\" ans"
+    ;;
+  "Build System")
+    foot -e bash -c "sudo nixos-rebuild switch --flake /home/falk/nix-conf#T480 --impure && echo \"==> Completed\" || echo \"==> Failed\"; read -p \"Press Key to Exit\" ans"
     ;;
   "  Go back")
     menu_main
